

services:
  untrunc-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: untrunc-web
    ports:
      - "5001:5001"  # Map port 5001 on the host to port 5001 in the container
    volumes:
      - ./shared:/app/shared
    environment:
      - FLASK_ENV=production  # Set Flask environment to production
      - UPLOAD_FOLDER=/app/shared/uploads
      - FIXED_FOLDER=/app/shared/fixed
    restart: unless-stopped  # Restart policy

volumes:
  nfs_share:
    external: true
